version: '1.0'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "5000:80"
    networks:
      - app

  network:
    build: ./network
    container_name: network
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - dashboard
    networks:
      - app

networks:
  app:
    driver: bridge
